/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_COURSE_WORK;

import java.util.ArrayList;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class BestInCustomers extends javax.swing.JFrame {

    /**
     * Creates new form BestInCustomers
     */
    public BestInCustomers() {
        initComponents();
        
        ArrayList<CustomerDetails> copiedPeople = new ArrayList<>();
        l1:for (CustomerDetails customers : PlaceOrder.CustomerList) {
            for (CustomerDetails uniqueCostomer : copiedPeople) {
                if (customers.getCusID().equals(uniqueCostomer.getCusID())) {
                    continue l1;
                }
            }
            copiedPeople.add(customers);

        }
        String[] customerId = new String[0];
        int[] totalqtQTY = new int[0];
        double[] totalAmount = new double[0];
        for (int i = 0; i < copiedPeople.size(); i++) {
            CustomerDetails uniqueCostomer = PlaceOrder.CustomerList.get(i);
            int qty = 0;
            double total = 0;
            for (CustomerDetails costomer : copiedPeople) {
                if (costomer.getCusID().equalsIgnoreCase(uniqueCostomer.getCusID())) {
                    qty += costomer.getQTY();
                    total += costomer.getAmount();
                }
            }
            customerId = Sourse.extendArrays(customerId);
            totalqtQTY = Sourse.extendArrays(totalqtQTY);
            totalAmount = Sourse.extendArrays(totalAmount);

            customerId[i] = uniqueCostomer.getCusID();
            totalqtQTY[i] = qty;
            totalAmount[i] = total;

        }
        for (int i = 0; i < customerId.length; i++) {
            for (int j = i; j < customerId.length; j++) {
                if (totalAmount[i] < totalAmount[j]) {
                    int tempvalue = totalqtQTY[i];
                    totalqtQTY[i] = totalqtQTY[j];
                    totalqtQTY[j] = tempvalue;

                    double tempvalue1 = totalAmount[i];
                    totalAmount[i] = totalAmount[j];
                    totalAmount[j] = tempvalue1;

                    String tempvalue3 = customerId[i];
                    customerId[i] = customerId[j];
                    customerId[j] = tempvalue3;
                }
            }
        }
        DefaultTableModel dtm= (DefaultTableModel) tblbestincus.getModel();
        dtm.setRowCount(0);
        
        DefaultTableCellRenderer rc = new DefaultTableCellRenderer();
        rc.setHorizontalAlignment(SwingConstants.CENTER);
        
        for (int i = 0; i < customerId.length; i++) {
            String qty = String.valueOf(totalqtQTY[i]);
            String printAmount=String.valueOf(totalAmount[i]);
            String[] values={customerId[i],qty,printAmount};
            dtm.addRow(values);
        }
        for (int i = 0; i < tblbestincus.getColumnCount(); i++) {
            tblbestincus.getColumnModel().getColumn(i).setCellRenderer(rc);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbestincus = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back.setBackground(new java.awt.Color(255, 0, 0));
        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        tblbestincus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tblbestincus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "QTY", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblbestincus);
        if (tblbestincus.getColumnModel().getColumnCount() > 0) {
            tblbestincus.getColumnModel().getColumn(1).setResizable(false);
            tblbestincus.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new ViewReports().setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BestInCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BestInCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BestInCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BestInCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BestInCustomers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbestincus;
    // End of variables declaration//GEN-END:variables
}
