/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_COURSE_WORK;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class PlaceOrder extends javax.swing.JFrame {

    public static Scanner input = new Scanner(System.in);
    public static final String[] size = {"XS", "S", "M", "L", "XL", "XXL"};
    public static final int[] price = {600, 800, 900, 1000, 1100, 1200};
    public static final String[] status = {"Processing", "Delivering", "Delivered"};
    public static String odr = "";
    public static int order = 0;
    static ArrayList<CustomerDetails> CustomerList = new ArrayList<>();

    public PlaceOrder() {
        initComponents();

        order++;
        String Sodr = String.format("%05d", order);
        odr = "ODR#" + Sodr;
        inputOdrID.setText(odr);
        inputCusID.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        inputOdrID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputCusID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputSize = new javax.swing.JTextField();
        inputQTY = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PrintAmount = new javax.swing.JLabel();
        place = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back.setBackground(new java.awt.Color(255, 51, 51));
        back.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        back.setForeground(java.awt.Color.white);
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Order ID : ");

        inputOdrID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Customer ID : ");

        inputCusID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inputCusID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCusIDActionPerformed(evt);
            }
        });
        inputCusID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputCusIDKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Size");

        inputSize.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inputSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputSizeKeyPressed(evt);
            }
        });

        inputQTY.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inputQTY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputQTYKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputQTYKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("QTY");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Amount");

        PrintAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        place.setBackground(new java.awt.Color(0, 153, 153));
        place.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        place.setForeground(new java.awt.Color(255, 255, 255));
        place.setText("Place");
        place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeActionPerformed(evt);
            }
        });
        place.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                placeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(place, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputCusID)
                            .addComponent(inputOdrID, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputSize, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(inputQTY, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(PrintAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputOdrID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCusID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSize, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PrintAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(place, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        order -= 1;
        new FashionShop().setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void inputCusIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCusIDKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
            if (inputCusID.getText().charAt(0) != '0' || inputCusID.getText().length() != 10) {
                JOptionPane.showMessageDialog(this, "Invalid Customer ID");
            } else {
                inputSize.requestFocus();
            }
        }
    }//GEN-LAST:event_inputCusIDKeyPressed

    private void inputSizeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSizeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
            String insertSize = inputSize.getText().toLowerCase();
            if (insertSize.equals("xs") || insertSize.equals("s") || insertSize.equals("m") || insertSize.equals("l") || insertSize.equals("xl") || insertSize.equals("xxl")) {
                inputQTY.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Size");
            }
        }
    }//GEN-LAST:event_inputSizeKeyPressed

    private void inputQTYKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputQTYKeyReleased
        if (inputQTY.getText().matches("\\d+")) {
            int qty = Integer.parseInt(inputQTY.getText());

            double amount = 0;
            switch (inputSize.getText().toLowerCase()) {
                case "xs":
                    amount = (600 * qty);
                    break;
                case "s":
                    amount = (800 * qty);
                    break;
                case "m":
                    amount = (900 * qty);
                    break;
                case "l":
                    amount = (1000 * qty);
                    break;
                case "xl":
                    amount = (1100 * qty);
                    break;
                case "xxl":
                    amount = (1200 * qty);
                    break;
                default:
                    break;
            }

            PrintAmount.setText(amount + "");

        } else {

        }


    }//GEN-LAST:event_inputQTYKeyReleased

    private void inputCusIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCusIDActionPerformed

    }//GEN-LAST:event_inputCusIDActionPerformed

    private void placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeActionPerformed
        String odrID = inputOdrID.getText();
        String cusID = inputCusID.getText();
        String size = inputSize.getText();
        int qty = Integer.parseInt(inputQTY.getText());
        double amount = Double.parseDouble(PrintAmount.getText());

        CustomerList.add(new CustomerDetails(odrID, cusID, amount, qty, size, status[0]));

        JOptionPane.showMessageDialog(this, "Order Placed");
        order++;
        String Sodr = String.format("%05d", order);
        odr = "ODR#" + Sodr;
        inputOdrID.setText(odr);
        inputCusID.setText("");
        inputSize.setText("");
        inputQTY.setText("");
        PrintAmount.setText("");

        inputCusID.requestFocus();
    }//GEN-LAST:event_placeActionPerformed

    private void placeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {
            placeActionPerformed(null);
        }

    }//GEN-LAST:event_placeKeyPressed

    private void inputQTYKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputQTYKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_TAB) {

        place.requestFocus();        // TODO add your handling code here:
        }
    }//GEN-LAST:event_inputQTYKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PrintAmount;
    private javax.swing.JButton back;
    private javax.swing.JTextField inputCusID;
    private javax.swing.JLabel inputOdrID;
    private javax.swing.JTextField inputQTY;
    private javax.swing.JTextField inputSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton place;
    // End of variables declaration//GEN-END:variables
}
