/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI_COURSE_WORK;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class ShortByQTY extends javax.swing.JFrame {

    /**
     * Creates new form ShortByQTY
     */
    public ShortByQTY() {
        initComponents();

        String[] sizesList = {"XS", "S", "M", "L", "XL", "XXL"};
        int[] QTY = new int[6];
        double[] Total = {0, 0, 0, 0, 0, 0};
        for (CustomerDetails customer : PlaceOrder.CustomerList) {
            switch (customer.getSize().toLowerCase()) {
                case "xs":
                    QTY[0] += customer.getQTY();
                    Total[0] += customer.getAmount();
                    break;
                case "s":
                    QTY[1] += customer.getQTY();
                    Total[1] = customer.getAmount();
                    break;
                case "m":
                    QTY[2] += customer.getQTY();
                    Total[2] = customer.getAmount();
                    break;
                case "l":
                    QTY[3] += customer.getQTY();
                    Total[3] = customer.getAmount();
                    break;
                case "xl":
                    QTY[4] += customer.getQTY();
                    Total[4] = customer.getAmount();
                    break;
                case "xxl":
                    QTY[5] += customer.getQTY();
                    Total[5] = customer.getAmount();
                    break;
            }
        }

        for (int i = 0; i < sizesList.length; i++) {
            for (int j = i; j < sizesList.length; j++) {
                if (QTY[i] < QTY[j]) {

                    int tempvalue = QTY[i];
                    QTY[i] = QTY[j];
                    QTY[j] = tempvalue;

                    double tempvalue1 = Total[i];
                    Total[i] = Total[j];
                    Total[j] = tempvalue1;

                    String tempvalue2 = sizesList[i];
                    sizesList[i] = sizesList[j];
                    sizesList[j] = tempvalue2;
                }
            }
        }
        DefaultTableModel dtm = (DefaultTableModel) shortByQTY.getModel();
        dtm.setRowCount(0);
        for (int i = 0; i < sizesList.length; i++) {
            String[] values = {sizesList[i], QTY[i] + "", Total[i] + ""};
            dtm.addRow(values);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        shortByQTY = new javax.swing.JTable();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        shortByQTY.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "size", "QTY", "Amount"
            }
        ));
        jScrollPane1.setViewportView(shortByQTY);
        if (shortByQTY.getColumnModel().getColumnCount() > 0) {
            shortByQTY.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ViewReports().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShortByQTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShortByQTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShortByQTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShortByQTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShortByQTY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable shortByQTY;
    // End of variables declaration//GEN-END:variables
}
